version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BINANCE_WS_URL=${BINANCE_WS_URL}
    ports:
      - 8080:8080
    volumes:
      - .:/app